#!bash.exe
if [ -z $1 ]; then
    echo Needs a file name;
    exit 1;
fi

if [ ! -e $1 ]; then
    echo $1: No such file or directory
    exit 1;
fi

filename=${1%.*};
pandoc $1 -o $filename.pdf --from markdown --highlight-style=tango;
ECHO Created $filename.pdf;
